[ECHOJS-90] tests for subscription
echoprotocol/echojs-lib pull request #16
Opened 2019-08-10 12:38 UTC by alesPoz

2019-08-14 08:26 UTC, nicklatkovich requested changes
@alesPoz , remove unused async/await

2019-08-14 08:26 UTC, nicklatkovich commented on src/echo/index.js
> +		this._wsApi = await new WSAPI(this._ws);
WSAPI's constructor no needs await

2019-08-14 08:26 UTC, nicklatkovich commented on src/echo/index.js
> +		try {
Duplicate

2019-08-14 11:51 UTC, nicklatkovich requested changes

2019-08-14 11:51 UTC, nicklatkovich commented on src/echo/ws-api/database-api.js
> +	async setSubscribeCallback(callback, notifyRemoveCreate) {
rm async

2019-08-14 11:51 UTC, nicklatkovich commented on src/echo/ws/index.js
> +     */
Use tab instead of spaces

2019-08-14 11:51 UTC, nicklatkovich commented on src/echo/ws/index.js
> -			console.error('[WS] >---- error ----->  ONOPEN', e);
What is a reason to remove?

2019-08-14 11:51 UTC, nicklatkovich commented on src/echo/ws/index.js
>  		return this._ws_rpc.reconnect();
Since the function is now async, it's better to return not a promise, but its result. Add await after return.

2019-08-14 11:51 UTC, nicklatkovich commented on src/echo/ws/reconnection-websocket.js
> +	async login(user, password, timeout = this._options.pingTimeout) {
rm async

2019-08-15 07:13 UTC, alesPoz commented on src/echo/ws/index.js
> -			console.error('[WS] >---- error ----->  ONOPEN', e);
it was not intentional

2019-08-15 12:40 UTC, nicklatkovich requested changes
When ws disconnected by connection interrupt (not by disconnect or reconnect methods), event "STATUS.CLOSE" emits by reconnection timeout

2019-08-15 12:40 UTC, nicklatkovich commented on src/echo/index.js
> +		this._ws.emit('STATUS.CLOSE');
Remove this emit

2019-08-19 16:10 UTC, nicklatkovich requested changes

2019-08-19 16:10 UTC, nicklatkovich commented on src/echo/subscriber.js
> +	constructor(ws) {
Add parameter in JSDoc

2019-08-19 16:10 UTC, nicklatkovich commented on src/echo/ws/index.js
> -
Avoid such changes

2019-08-19 16:10 UTC, nicklatkovich commented on src/echo/ws/index.js
> +	*/
Return space in JSDoc

2019-08-19 16:10 UTC, nicklatkovich commented on src/echo/ws/reconnection-websocket.js
> +
rm

2019-08-19 16:10 UTC, nicklatkovich commented on src/echo/ws/reconnection-websocket.js
> +
rm

2019-08-20 11:39 UTC, nicklatkovich approved these changes

2019-08-20 11:40 UTC, merged