[ECHOJS-148] serialize methods  and arguments
echoprotocol/echojs-lib pull request #56
Opened 2019-09-12 08:38 UTC by alesPoz

2019-09-25 11:59 UTC, nicklatkovich requested changes

2019-09-25 11:59 UTC, nicklatkovich commented on src/echo/ws-api/wallet-api.js
> +		if (!limit > API_CONFIG.LIST_ACCOUNTS_MAX_LIMIT) {
`!limit` is always equals to `false` or `true`. So this field will be valid in any way.
Remove `!` here and below.

2019-09-25 11:59 UTC, nicklatkovich commented on src/serializers/basic/VariantObject.js
> +/** @typedef {SerializerInput<array.<any>>} TInput */
```js
 /** @typedef {[string, any]} TInput */
```

2019-09-25 11:59 UTC, nicklatkovich commented on src/serializers/basic/VariantObject.js
> +/** @typedef {array.<any>} TOutput */
```js
/** @typedef {[string, any]} TOutput */
```

2019-09-25 11:59 UTC, nicklatkovich commented on src/serializers/basic/VariantObject.js
> +	 * @param {TInput<T>} value
Genesis is not needed here
```js
* @param {TInput} value
```

2019-09-25 11:59 UTC, nicklatkovich commented on src/serializers/basic/VariantObject.js
> +		return value;
validate, that the first element is string

2019-09-25 11:59 UTC, nicklatkovich commented on src/serializers/basic/VariantObject.js
> +	 * @returns {TOutput<T>}
rm genesis

2019-09-25 11:59 UTC, nicklatkovich commented on src/serializers/basic/index.js
>  export { integers, BoolSerializer, BytesSerializer, TimePointSecSerializer };
export `VariantObjectSerializer`

2019-09-25 11:59 UTC, nicklatkovich commented on src/serializers/index.js
> +export { accountListing } from './protocol/account/index';
export `accountListing` in `protocol/index` (like `price` of asset)
rm from here

2019-09-25 11:59 UTC, nicklatkovich commented on src/serializers/index.js
> +export { approvalDelta } from './wallet';
make wallet module (like `protocol`)

2019-09-25 11:59 UTC, nicklatkovich commented on src/serializers/index.js
> +export { accountListing } from './protocol/account/index';
`AccountListingSerializer` and `ACCOUNT_LISTING` too

2019-09-25 11:59 UTC, nicklatkovich commented on types/serializers/basic/VariantObject.d.ts
> +type TInput = Array<any>;
```ts
type TInput = [string, any];
```

2019-09-25 11:59 UTC, nicklatkovich commented on types/serializers/basic/VariantObject.d.ts
> +type TOutput = Array<any>;
```ts
type TOutput = [string, any];
```

2019-09-25 11:59 UTC, nicklatkovich commented on src/serializers/basic/VariantObject.js
> +	appendToByteBuffer() {
You need to implement `readFromBuffer` abstract method like this one

2019-09-25 11:59 UTC, nicklatkovich commented on src/serializers/basic/VariantObject.js
> +	appendToByteBuffer() {
In `PrivateKeySerializer` too

2019-09-25 21:49 UTC, alesPoz commented on src/serializers/index.js
> +export { approvalDelta } from './wallet';
Sorry, i didn't catch your idea

2019-10-03 08:28 UTC, nicklatkovich requested changes

2019-10-03 08:28 UTC, nicklatkovich commented on types/serializers/wallet.d.ts
> +export default approvalDelta;
Remove `export default` and use `export` (your declaration files should duplicate structure of JS-files)

2019-10-03 08:28 UTC, nicklatkovich commented on src/serializers/protocol/account/account_listing.js
> +	}
Function does not returns value

2019-10-03 08:28 UTC, nicklatkovich commented on types/serializers/protocol/account/account_listing.d.ts
> +    toRaw(value: number): number;
`number` >> `ACCOUNT_LISTING`

2019-10-03 08:28 UTC, nicklatkovich commented on src/serializers/protocol/account/account_listing.js
> +
Create jsdoc-enum type
```ts
/**
 * @typedef {Object} ACCOUNT_LISTING_t
 * @property {0x0} NO_LISTNING
 * @property {0x1} WHITE_LISTED
 * @property {0x2} BLACK_LISTED
 * @property {0x3} WHITE_AND_BLACK_LISTED
 */
```

2019-10-03 08:28 UTC, nicklatkovich commented on src/serializers/protocol/account/account_listing.js
> +
And add this type as type of const ACCOUNT_LISTING
```ts
/** @type {ACCOUNT_LISTING_t} */
 export const ACCOUNT_LISTING = {
// ...
```

2019-10-03 08:28 UTC, nicklatkovich commented on src/serializers/protocol/account/account_listing.js
> +
And fix JSDoc of `toRaw` method to
```ts
/**
 * @template {ACCOUNT_LISTING_t[keyof ACCOUNT_LISTING_t]} T
 * @param {T} value
 * @returns {T}
 */```

2019-10-03 08:28 UTC, nicklatkovich commented on src/serializers/index.js
> +import * as approvalDelta from './wallet';
Invalid input format. To use approvalDelta i will need to use something like:
```ts
import { serializers } from "echojs-lib"
serializers.approvalDelta.approvalDelta
```
Change name of this import to wallet to use this serializer like:
```ts
import { serializers } from "echojs-lib"
serializers.wallet.approvalDelta
```

2019-10-03 08:28 UTC, nicklatkovich commented on src/serializers/index.js
> +import * as approvalDelta from './wallet';
And add changes of this files to declaration files

2019-10-03 08:28 UTC, nicklatkovich commented on src/serializers/chain/index.js
>  import * as ids from './id';
Add changes of this files to declaration-files

2019-10-03 08:28 UTC, nicklatkovich commented on src/serializers/basic/index.js
> +import VariantObjectSerializer from './VariantObject';
Add in delcaration-files

2019-10-07 11:53 UTC, nicklatkovich requested changes

2019-10-07 11:53 UTC, nicklatkovich commented on src/serializers/index.js
> +export { basic, collections, chain, OperationSerializer, plugins, protocol, opWrapper, wallet };
exporting of wallet is not provided in declaration files

2019-10-07 11:53 UTC, nicklatkovich commented on src/serializers/protocol/index.js
> +export { AccountListingSerializer, accountListing, ACCOUNT_LISTING } from './account';
this code is not provided in declaration files

2019-10-07 11:53 UTC, nicklatkovich commented on src/echo/ws-api/wallet-api.js
> +			wallet.toRaw(delta),
`wallet` is collection of wallet-serializators. It has no method `toRaw`. Use `wallet.approvalDelta.toRaw`.

2019-10-08 09:19 UTC, nicklatkovich approved these changes

2019-10-08 09:20 UTC, merged