[ECHOJS-169] implement freeze_balance and list_frozen_balances methods
echoprotocol/echojs-lib pull request #66
Opened 2019-10-03 07:07 UTC by adziaryba

was implemented freeze_balance and list_frozen_balances from wallet-api, added tests

2019-10-07 15:11 UTC, chralsia approved these changes

2019-10-08 09:56 UTC, nicklatkovich requested changes

2019-10-08 09:56 UTC, nicklatkovich commented on src/echo/ws-api/wallet-api.js
> +			throw new Error('Account name or id is invalid');
```ts
return Promise.reject(new Error('Account name or id is invalid'))
```

2019-10-08 09:56 UTC, nicklatkovich commented on src/echo/ws-api/wallet-api.js
> +			throw new Error('Accounts id or name should be string and valid');
```ts
return Promise.reject(new Error('Accounts id or name should be string and valid'))
```

2019-10-08 09:56 UTC, nicklatkovich commented on src/echo/ws-api/wallet-api.js
> +		if (!isAssetId(assetIdOrName) || isAssetName(assetIdOrName)) throw new Error('Asset id or name is invalid');
```ts
return Promise.reject(new Error('Asset id or name is invalid'))
```

2019-10-08 10:20 UTC, nicklatkovich approved these changes

2019-10-10 16:18 UTC, merged