[ECHOJS-178] implement registerAccountWithProof method
echoprotocol/echojs-lib pull request #68
Opened 2019-10-03 09:34 UTC by adziaryba

implement register_account_with_proof method for wallet-api

2019-10-07 15:16 UTC, chralsia approved these changes

2019-10-08 10:23 UTC, nicklatkovich requested changes

2019-10-08 10:23 UTC, nicklatkovich commented on src/echo/ws-api/wallet-api.js
> +		if (!isPublicKey(echorandKey)) throw new Error('echorand key is invalid');
```ts
return Promise.reject(new Error('...'));
```

2019-10-08 22:00 UTC, nicklatkovich approved these changes

2019-10-10 16:58 UTC, merged